import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { Card, Grid, Text } from '@nextui-org/react';
import { gql, useQuery } from '@apollo/client';
import type { IReport } from '@package-inspector/pi-cli';

import styles from '../styles/Home.module.css';

interface Report extends IReport {
  summary: string;
}

interface ReportData {
  report: Report;
}

const ReportQuery = gql`
  query {
    report {
      summary
      package {
        name
        version
        dependencies {
          name
          type
          version
        }
      }
      suggestions {
        id
        name
        message
        actions {
          message
        }
      }
    }
  }
`;

const Home: NextPage = () => {
  const { data, loading, error } = useQuery<ReportData>(ReportQuery);

  if (loading) return <p>Loading...</p>;
  if (error) return <p>Oh no... {error.message}</p>;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <Link href="/report">{data?.report.package.name}</Link>
          <p>{data?.report.summary}</p>
        </h1>

        <Grid.Container gap={2} justify={'center'}>
          {data &&
            data.report.suggestions.map((suggestion) => (
              <Grid sm={12} md={3} key={suggestion.id}>
                <Card>
                  <Text h4>{suggestion.name}</Text>
                  <Text>{suggestion.message}</Text>
                  <Card.Footer>{suggestion.actions.length} actions</Card.Footer>
                </Card>
              </Grid>
            ))}
        </Grid.Container>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
