import * as React from 'react';
import Head from 'next/head';
import Image from 'next/image';

// FIXME: this should be the layout styles
import styles from '../styles/Home.module.css';

import { Container } from '@mui/material';

import Navbar from '../components/Navbar';

// FIXME: needs to extend from base props correctly
export const Layout = ({
  title,
  children,
}: {
  title: string;
  children: any;
}) => {
  return (
    <div>
      <Head>
        <title>Package Inspector</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar title={title} />

      <Container sx={{ py: 8 }} maxWidth="md">
        {children}
      </Container>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};
