import { Container } from '@mui/material';
import Head from 'next/head';
import Link from 'next/link';
import * as React from 'react';

import Navbar from '../components/Navbar';
import styles from './Layout.module.css';

type LayoutProps = React.PropsWithChildren<{
  title: string;
  hero?: React.FC;
}>;

export const Layout: React.FC<LayoutProps> = ({ title, hero, children }) => {
  return (
    <>
      <Head>
        <title>Package Inspector</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar title={title} />

      {hero ? hero : null}

      <Container sx={{ py: 8, backgroundColor: 'grey.100' }} maxWidth={false}>
        {children}
      </Container>

      <footer className={styles.footer}>
        Powered by &nbsp;
        <span>
          <Link href="https://github.com/es-maintenance/package-inspector">
            es-maintenance@package-inspector
          </Link>
        </span>
      </footer>
    </>
  );
};
