import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { Card, Grid, Text } from '@nextui-org/react';
import { gql, useQuery } from '@apollo/client';

import type { Report as IReport } from '@package-inspector/core';

import { NexusGenFieldTypes } from '../graphql/generated/nexus-typegen';
import SuggestionOverview from '../components/SuggestionOverview';

import styles from '../styles/Home.module.css';

// TODO: This is being used in SuggestionOverview because we are passing the query report result to it, need to refactor this
export type Report = NexusGenFieldTypes['Report'];

// TODO: figure out how to Pick from other picks
interface ReportData {
  report: Pick<NexusGenFieldTypes['Report'], 'summary' | 'root'>;
}

const ReportQuery = gql`
  query {
    report {
      summary
      root {
        name
        version
      }
    }
  }
`;

const Home: NextPage = () => {
  const { data, loading, error } = useQuery<ReportData>(ReportQuery);

  if (loading) return <p>Loading...</p>;
  if (error) return <p>Oh no... {error.message}</p>;
  if (!data) return <p>Oh no... could not load report</p>;

  console.log(data.report);
  return (
    <div className={styles.container}>
      <Head>
        <title>Package Inspector</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <Link href="/report">{data.report.root.name}</Link>
        </h1>

        {/* TODO: we need to talk about this */}
        {/* <SuggestionOverview report={data.report} /> */}

        <Grid.Container gap={2} justify={'center'}>
          <h2>TODO: Suggestions not impl yet</h2>
          {/* {data &&
            data.report.suggestions.map((suggestion) => (
              <Grid sm={12} md={3} key={suggestion.id}>
                <Card>
                  <Text h4>{suggestion.name}</Text>
                  <Text>{suggestion.message}</Text>
                  <Card.Footer>{suggestion.actions.length} actions</Card.Footer>
                </Card>
              </Grid>
            ))} */}
        </Grid.Container>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
