# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Verify Build

    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Volta
        uses: volta-cli/action@v1.7.0
      - name: Install Dependencies
        run: yarn install
      - name: Build Workspaces
        run: yarn build

  test:
    name: Run Tests

    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Volta
        uses: volta-cli/action@v1.7.0
      - name: Install Dependencies
        run: yarn install
      - name: Build Workspaces
        run: yarn build
      - name: Lint Workspaces
        run: yarn lint:ci
      - name: Test Workspaces
        run: yarn test:ci
